# Generated by Django 4.2.4 on 2023-08-31 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_customuser_groups_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
    ]
