# Generated by Django 4.2.4 on 2023-09-02 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_like'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='like',
            table='like',
        ),
    ]
