# Generated by Django 4.2.4 on 2023-09-02 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_rename_post_id_postlike_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlike',
            name='updated_at',
        ),
    ]
