# Generated by Django 4.2.4 on 2023-09-03 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0018_comment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='users',
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
    ]
