# Generated by Django 4.2.4 on 2023-09-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0019_alter_comment_table_alter_customuser_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(null=True, upload_to='user_img'),
        ),
    ]
