# Generated by Django 4.2.4 on 2023-09-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0020_customuser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='image',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profile_image'),
        ),
    ]
