# Generated by Django 4.2.4 on 2023-09-06 07:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0022_alter_customuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(code='invalid_alphanumeric', message='영어, 숫자 조합만 가능합니다.', regex='^[a-zA-Z0-9]+$')]),
        ),
    ]
